version: "3.9"

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: apocalipssi-frontend
    ports:
      - "3000:80"
    networks:
      - appnet
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: pdf-analyzer-backend
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - mongodb
      - ollama
    networks:
      - appnet
    restart: unless-stopped

  mongodb:
    image: mongo:6
    container_name: apocalipssi-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - appnet
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: mistral-local
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - appnet
    restart: unless-stopped
    tty: true
    command: >
      bash -c "
        ollama pull mistral &&
        ollama run mistral
      "

volumes:
  mongodb_data:
  ollama_data:

networks:
  appnet:
    driver: bridge
