name: CI Node.js

on:
  push:
    branches: [ kevin ]
  pull_request:
    branches: [ kevin ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installer les dépendances
        run: cd server && npm install

      - name: Démarrer MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: '6.0'

      - name: Lancer les tests
        run: cd server && npm test
